// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.28.2
// source: internal/models/protomodels/pong_game.proto

package pong

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Player struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name  string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Score int32  `protobuf:"varint,3,opt,name=score,proto3" json:"score,omitempty"`
}

func (x *Player) Reset() {
	*x = Player{}
	mi := &file_internal_models_protomodels_pong_game_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Player) ProtoMessage() {}

func (x *Player) ProtoReflect() protoreflect.Message {
	mi := &file_internal_models_protomodels_pong_game_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Player.ProtoReflect.Descriptor instead.
func (*Player) Descriptor() ([]byte, []int) {
	return file_internal_models_protomodels_pong_game_proto_rawDescGZIP(), []int{0}
}

func (x *Player) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Player) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Player) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

type Ball struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X  float32 `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y  float32 `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	Vx float32 `protobuf:"fixed32,3,opt,name=vx,proto3" json:"vx,omitempty"`
	Vy float32 `protobuf:"fixed32,4,opt,name=vy,proto3" json:"vy,omitempty"`
}

func (x *Ball) Reset() {
	*x = Ball{}
	mi := &file_internal_models_protomodels_pong_game_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ball) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ball) ProtoMessage() {}

func (x *Ball) ProtoReflect() protoreflect.Message {
	mi := &file_internal_models_protomodels_pong_game_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ball.ProtoReflect.Descriptor instead.
func (*Ball) Descriptor() ([]byte, []int) {
	return file_internal_models_protomodels_pong_game_proto_rawDescGZIP(), []int{1}
}

func (x *Ball) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Ball) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Ball) GetVx() float32 {
	if x != nil {
		return x.Vx
	}
	return 0
}

func (x *Ball) GetVy() float32 {
	if x != nil {
		return x.Vy
	}
	return 0
}

type PongGameState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Player1    *Player `protobuf:"bytes,1,opt,name=player1,proto3" json:"player1,omitempty"`
	Player2    *Player `protobuf:"bytes,2,opt,name=player2,proto3" json:"player2,omitempty"`
	Ball       *Ball   `protobuf:"bytes,3,opt,name=ball,proto3" json:"ball,omitempty"`
	HasStarted bool    `protobuf:"varint,4,opt,name=hasStarted,proto3" json:"hasStarted,omitempty"`
}

func (x *PongGameState) Reset() {
	*x = PongGameState{}
	mi := &file_internal_models_protomodels_pong_game_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PongGameState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PongGameState) ProtoMessage() {}

func (x *PongGameState) ProtoReflect() protoreflect.Message {
	mi := &file_internal_models_protomodels_pong_game_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PongGameState.ProtoReflect.Descriptor instead.
func (*PongGameState) Descriptor() ([]byte, []int) {
	return file_internal_models_protomodels_pong_game_proto_rawDescGZIP(), []int{2}
}

func (x *PongGameState) GetPlayer1() *Player {
	if x != nil {
		return x.Player1
	}
	return nil
}

func (x *PongGameState) GetPlayer2() *Player {
	if x != nil {
		return x.Player2
	}
	return nil
}

func (x *PongGameState) GetBall() *Ball {
	if x != nil {
		return x.Ball
	}
	return nil
}

func (x *PongGameState) GetHasStarted() bool {
	if x != nil {
		return x.HasStarted
	}
	return false
}

var File_internal_models_protomodels_pong_game_proto protoreflect.FileDescriptor

var file_internal_models_protomodels_pong_game_proto_rawDesc = []byte{
	0x0a, 0x2b, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f, 0x70, 0x6f,
	0x6e, 0x67, 0x5f, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x42, 0x0a,
	0x06, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73,
	0x63, 0x6f, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x73, 0x63, 0x6f, 0x72,
	0x65, 0x22, 0x42, 0x0a, 0x04, 0x42, 0x61, 0x6c, 0x6c, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x01, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x76, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x02, 0x76, 0x78, 0x12, 0x0e, 0x0a, 0x02, 0x76, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x02, 0x76, 0x79, 0x22, 0x90, 0x01, 0x0a, 0x0d, 0x50, 0x6f, 0x6e, 0x67, 0x47, 0x61,
	0x6d, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x21, 0x0a, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x52, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x31, 0x12, 0x21, 0x0a, 0x07, 0x70, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x32, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x50, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x52, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x32, 0x12, 0x19, 0x0a,
	0x04, 0x62, 0x61, 0x6c, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x42, 0x61,
	0x6c, 0x6c, 0x52, 0x04, 0x62, 0x61, 0x6c, 0x6c, 0x12, 0x1e, 0x0a, 0x0a, 0x68, 0x61, 0x73, 0x53,
	0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x68, 0x61,
	0x73, 0x53, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x42, 0x22, 0x5a, 0x20, 0x68, 0x61, 0x6e, 0x64,
	0x67, 0x61, 0x6d, 0x65, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x70, 0x6f, 0x6e, 0x67, 0x2f, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_models_protomodels_pong_game_proto_rawDescOnce sync.Once
	file_internal_models_protomodels_pong_game_proto_rawDescData = file_internal_models_protomodels_pong_game_proto_rawDesc
)

func file_internal_models_protomodels_pong_game_proto_rawDescGZIP() []byte {
	file_internal_models_protomodels_pong_game_proto_rawDescOnce.Do(func() {
		file_internal_models_protomodels_pong_game_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_models_protomodels_pong_game_proto_rawDescData)
	})
	return file_internal_models_protomodels_pong_game_proto_rawDescData
}

var file_internal_models_protomodels_pong_game_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_internal_models_protomodels_pong_game_proto_goTypes = []any{
	(*Player)(nil),        // 0: Player
	(*Ball)(nil),          // 1: Ball
	(*PongGameState)(nil), // 2: PongGameState
}
var file_internal_models_protomodels_pong_game_proto_depIdxs = []int32{
	0, // 0: PongGameState.player1:type_name -> Player
	0, // 1: PongGameState.player2:type_name -> Player
	1, // 2: PongGameState.ball:type_name -> Ball
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_internal_models_protomodels_pong_game_proto_init() }
func file_internal_models_protomodels_pong_game_proto_init() {
	if File_internal_models_protomodels_pong_game_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_models_protomodels_pong_game_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_models_protomodels_pong_game_proto_goTypes,
		DependencyIndexes: file_internal_models_protomodels_pong_game_proto_depIdxs,
		MessageInfos:      file_internal_models_protomodels_pong_game_proto_msgTypes,
	}.Build()
	File_internal_models_protomodels_pong_game_proto = out.File
	file_internal_models_protomodels_pong_game_proto_rawDesc = nil
	file_internal_models_protomodels_pong_game_proto_goTypes = nil
	file_internal_models_protomodels_pong_game_proto_depIdxs = nil
}
